.\"     Title: smugls
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: May 2008
.\"    Manual: smugls
.\"    Source: smugls
.\"
.TH "SMUGLS" "3" "May 2008" "smugls" "smugls"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
smugls - list files in a smugmug.com gallery
.SH "SYNOPSIS"
.HP 7
\fBsmugls\fR [\fB\-\-email\ email@address\fR] [\fB\-\-password\ password\fR] [\fB\-\-album\ album\fR] [\fB\-\-debug\fR] [\fB\-\-version\fR] [\fB\-\-help\fR]
.SH "DESCRIPTION"
.PP
smugls lists all of the files in a specified smugmug\.com gallery\.
.SH "OPTIONS"
.PP
\fB\-\-email email@address\fR
.RS 4
Specify the email address of your smugmug\.com account\.
.RE
.PP
\fB\-\-password password\fR
.RS 4
Specify the password of your smugmug\.com account\.
.RE
.PP
\fB\-\-debug\fR
.RS 4
Print a whole bunch of debugging messages to stdout\.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print version number\.
.RE
.PP
\fB\-\-help\fR
.RS 4
Print help text\.
.RE
.SH "AUTHOR"
.PP
Written by Greg Kroah\-Hartman
<greg@kroah\.com>\.
.SH "SEE ALSO"
.PP
\fBsmugup\fR(7),
\fBsmugdown\fR(7)
